export const productItems = [
    {
        id: 1,
        image: 'src/assets/s1.jpeg',
        alt: 'image 1',
        pricing: 301,
        title: 'sweatshirt 1',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 2,
        image: 'src/assets/s2.jpeg',
        alt: 'image 2',
        pricing: 302,
        title: 'sweatshirt 2',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 3,
        image: 'src/assets/s3.jpeg',
        alt: 'image 3',
        pricing: 303,
        title: 'sweatshirt 3',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 4,
        image: 'src/assets/s4.jpeg',
        alt: 'image 4',
        pricing: 304,
        title: 'sweatshirt 4',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 5,
        image: 'src/assets/s5.jpeg',
        alt: 'image 5',
        pricing: 305,
        title: 'sweatshirt 5',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 6,
        image: 'src/assets/s6.jpeg',
        alt: 'image 6',
        pricing: 306,
        title: 'sweatshirt 6',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 7,
        image: 'src/assets/s7.jpeg',
        alt: 'image 7',
        pricing: 307,
        title: 'sweatshirt 7',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 8,
        image: 'src/assets/s8.jpeg',
        alt: 'image 8',
        pricing: 308,
        title: 'sweatshirt 8',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 9,
        image: 'src/assets/s9.jpeg',
        alt: 'image 9',
        pricing: 309,
        title: 'sweatshirt 1',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 10,
        image: 'src/assets/s10.jpeg',
        alt: 'image 10',
        pricing: 310,
        title: 'sweatshirt 10',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 11,
        image: 'src/assets/s11.jpeg',
        alt: 'image 11',
        pricing: 311,
        title: 'sweatshirt 11',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 12,
        image: 'src/assets/s12.jpeg',
        alt: 'image 12',
        pricing: 312,
        title: 'sweatshirt 12',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 13,
        image: 'src/assets/s13.jpeg',
        alt: 'image 13',
        pricing: 313,
        title: 'sweatshirt 13',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 14,
        image: 'src/assets/s14.jpeg',
        alt: 'image 14',
        pricing: 314,
        title: 'sweatshirt 14',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 15,
        image: 'src/assets/s15.jpeg',
        alt: 'image 15',
        pricing: 315,
        title: 'sweatshirt 15',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 16,
        image: 'src/assets/s16.jpeg',
        alt: 'image 16',
        pricing: 316,
        title: 'sweatshirt 16',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 17,
        image: 'src/assets/s17.jpeg',
        alt: 'image 17',
        pricing: 317,
        title: 'sweatshirt 17',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 18,
        image: 'src/assets/s18.jpeg',
        alt: 'image 18',
        pricing: 318,
        title: 'sweatshirt 18',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 19,
        image: 'src/assets/s19.jpeg',
        alt: 'image 19',
        pricing: 319,
        title: 'sweatshirt 19',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 20,
        image: 'src/assets/s20.jpeg',
        alt: 'image 20',
        pricing: 320,
        title: 'sweatshirt 20',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 21,
        image: 'src/assets/s21.jpeg',
        alt: 'image 21',
        pricing: 321,
        title: 'sweatshirt 21',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 22,
        image: 'src/assets/s22.jpeg',
        alt: 'image 22',
        pricing: 322,
        title: 'sweatshirt 22',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 23,
        image: 'src/assets/s23.jpeg',
        alt: 'image 23',
        pricing: 323,
        title: 'sweatshirt 23',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 24,
        image: 'src/assets/s24.jpeg',
        alt: 'image 24',
        pricing: 324,
        title: 'sweatshirt 24',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 25,
        image: 'src/assets/s25.jpeg',
        alt: 'image 25',
        pricing: 325,
        title: 'sweatshirt 25',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 26,
        image: 'src/assets/s26.jpeg',
        alt: 'image 26',
        pricing: 326,
        title: 'sweatshirt 26',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 27,
        image: 'src/assets/s27.jpeg',
        alt: 'image 27',
        pricing: 327,
        title: 'sweatshirt 27',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },
    {
        id: 28,
        image: 'src/assets/s28.jpeg',
        alt: 'image 28',
        pricing: 328,
        title: 'sweatshirt 28',
        qty: 1,
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, repudiandae quas sint vel perferendis voluptatibus quos praesentium hic vero necessitatibus.',
        size: {
            L: 'USA: 7.5, UK: 7, EU: 41',
            LM: 'USA: 8, UK: 8, EU: 42',
            XL: 'USA: 8.5, UK: 9, EU: 43',
            XL2: 'USA: 9, UK: 10, EU: 44',
            XXL: 'USA: 10, UK: 11, EU: 45',
        }
    },

]

